# Generated by Django 4.1.2 on 2022-11-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("website", models.CharField(blank=True, max_length=100, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("founded", models.IntegerField(blank=True, null=True)),
                ("size", models.CharField(blank=True, max_length=10, null=True)),
                ("locality", models.CharField(blank=True, max_length=100, null=True)),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("industry", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "linkedin_url",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
    ]
